config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get '/contacto' => 'contact#new'
  post "/contacto" => "contact#contact_form", as: :contact
  post "/feedback" => "contact#feedback", as: :feedback
  get '/about' => "main#about"
  get '/marcas' => "main#brands"

  resources :brands, only: [:show], path: '/marcas'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true
  validates :logo, presence: {message: "no puede estar vacío"}
  validates :image1, presence: {message: "no puede estar vacío"}
  validates :image2, presence: {message: "no puede estar vacío"}
  validates :image3, presence: {message: "no puede estar vacío"}
  has_one :detail, dependent: :destroy

  has_attached_file :logo, 
  url: "/images/brands/:id/:style/:basename.:extension"
  validates_attachment :logo, content_type: { content_type: 
    ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  has_attached_file :image1, 
  url: "/images/brands/:id/:style/:basename.:extension"
  validates_attachment :image1, content_type: { content_type: 
    ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  has_attached_file :image2, 
  url: "/images/brands/:id/:style/:basename.:extension"
  validates_attachment :image2, content_type: { content_type: 
    ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  has_attached_file :image3, 
  url: "/images/brands/:id/:style/:basename.:extension"
  validates_attachment :image3, content_type: { content_type: 
    ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/detail.rb
class Detail < ActiveRecord::Base
  validates :brand_id, presence: {message: "debe elegir una marca"}
  validates :open_hour, presence: {message: "no puede estar vacío"}
  validates :close_hour, presence: {message: "no puede estar vacío"}
  belongs_to :brand
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
  validates :image, presence: {message:'no puede estar vacío'}
  has_attached_file :image, 
  url: "/images/events/:id/:style/:basename.:extension"
  validates_attachment :image, content_type: { content_type: 
    ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/feedback.rb
class Feedback
  include ActiveModel::Model
  attr_accessor :email, :message

  validates_presence_of :email
  validates_presence_of :message
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :subject, :message

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :subject
  validates_presence_of :message
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    '/admin'
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def show
    @brand = Brand.friendly.find(params[:id])
    @details = @brand.detail
    @brands = Brand.all
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
  end
  def contact_form
    message = Message.new(params[:contact_form])
    if message.valid?
      Contact.contact(message).deliver
      flash[:notice] = "Mensaje enviado. Gracias por contactarnos"
      render :new
    else
      flash[:alert] = "Mensaje no enviado. Asegúrate de completar todos los campos."
      render :new
    end
  end
  def feedback
    message = Feedback.new(params[:feedback])
    if message.valid?
      Contact.feedback(message).deliver
      flash[:notice] = "Mensaje enviado. Gracias por contactarnos"
      redirect_to :back
    else
      flash[:alert] = "Mensaje no enviado. Asegúrate de completar todos los campos."
      redirect_to :back
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @events = Event.all.order("created_at DESC")
  end

  def about
    @brands = Brand.all.order("created_at DESC")
  end

  def brands
    @brands = Brand.all.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/brands/show.html.erb
<!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img src="<%= image_path('logo.png') %>"></a>
        </div>
        <div class="navbar-collapse collapse navbar-right">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <li><a href="/about">Novo Pacheco</a></li>
            <li class="active"><a href="/marcas">Marcas</a></li>
            <li><a href="/contacto">Contacto</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <% if flash.notice %>
      <div class="alert alert-success">
        <%= flash.notice %>  
      </div>
    <% end %>
    <% if flash.alert %>
      <div class="alert alert-danger">
        <%= flash.alert %>  
      </div>
    <% end %>

  <!-- *****************************************************************************************************************
   TITLE & CONTENT
   ***************************************************************************************************************** -->

   <div class="container mt">
    <div class="row">
      <div class="col-lg-10 col-lg-offset-1 centered">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
          </ol>
        
          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <div class="item active">
              <img src="<%= @brand.image1.url %>" alt="">
            </div>
            <div class="item">
              <img src="<%= @brand.image2.url %>" alt="">
            </div>
            <div class="item">
              <img src="<%= @brand.image3.url %>" alt="">
            </div>
          </div>
        </div><!--/Carousel -->
      </div>
      
      <div class="col-lg-5 col-lg-offset-1">
        <div class="spacing"></div>
        <h4><%= @brand.name %></h4>
        <p><%= @brand.description %></p>
        <h4>Además</h4>
        <p><%= @brand.besides %></p>
      </div>
      
      <div class="col-lg-4 col-lg-offset-1">
        <div class="spacing"></div>
        <h4>Detalles</h4>
        <div class="hline"></div>
        <p>
          <b>Horario de atención:</b>
          <%= @details.open_hour.strftime("%H:%M") %>hs a <%= @details.close_hour.strftime("%H:%M") %>hs</p>
        <p>
          <% if @details.present? && @details.location.present? %>
            <b>Ubicación:</b>
            <%= @details.location %>
          <% end %>
        </p>
        <p>
          <% if @details.present? && @details.web.present? %>
            <b>Web:</b> <%= @details.web %>
          <% end %>
        </p>
        <p>
          <% if @details.present? && @details.facebook.present? %>
            <b>Facebook:</b>
            <%= @details.facebook %>
          <% end %>
        </p>
      </div>  
    </div><!--/row -->
   </div><!--/container -->
   
  <!-- *****************************************************************************************************************
   PORTFOLIO SECTION
   ***************************************************************************************************************** -->
<div id="portfoliowrap">
  <div class="portfolio-centered">
    <h3>Otras marcas</h3>
    <div class="recentitems portfolio">
      <% @brands.each do |b| %>
        <% if b.id != @brand.id %>
          <div class="portfolio-item graphic-design">
            <div class="he-wrap tpl6">
              <img src="<%= b.logo.url %>" alt="">
              <div class="he-view">
                <div class="bg a0" data-animate="fadeIn">
                  <h3 class="a1" data-animate="fadeInDown">Conocé el local</h3>
                  <a data-rel="prettyPhoto" href="<%= b.logo.url %>"></a>
                  <%= link_to 'Ver más', brand_path(b), class: 'dmbutton a2', "data-animate" => "fadeInUp"%>
                </div><!-- he bg -->
              </div><!-- he view -->    
            </div><!-- he wrap -->
          </div><!-- end col-12 -->
        <% end %>  
      <% end %>  
    </div><!-- portfolio -->
  </div><!-- portfolio container -->
</div><!--/Portfoliowrap -->

app/views/contact/contact.html.erb
<h1><%= @message.name %></h1>
<h2><%= @message.email %></h2>
<h3><%= @message.subject%></h3>
<%= @message.message%>

app/views/contact/feedback.html.erb
<h2><%= @message.email %></h2>
<%= @message.message%>

app/views/contact/new.html.erb
<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img src="<%= image_path('logo.png') %>"></a>
    </div>
    <div class="navbar-collapse collapse navbar-right">
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
        <li><a href="/about">Novo Pacheco</a></li>
        <li><a href="/marcas">Marcas</a></li>
        <li class="active"><a href="/contacto">Contacto</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<% if flash.notice %>
  <div class="alert alert-success">
    <%= flash.notice %>  
  </div>
<% end %>
<% if flash.alert %>
  <div class="alert alert-danger">
    <%= flash.alert %>  
  </div>
<% end %>


  <!-- *****************************************************************************************************************
   CONTACT WRAP
   ***************************************************************************************************************** -->

   <iframe id="gmap" src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d5786.836632775678!2d-58.620379031643125!3d-34.47024157566476!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sav+boulogne+sur+mer+1200+general+pacheco!5e0!3m2!1ses!2sar!4v1436497694300" width="1260" height="400" frameborder="0" style="border:0" allowfullscreen></iframe>
   
  <!-- *****************************************************************************************************************
   CONTACT FORMS
   ***************************************************************************************************************** -->

   <div class="container mtb">
    <div class="row">
      <div class="col-lg-8">
        <h4>Pongase en contacto!</h4>
        <div class="hline"></div>
          <p>Ante cualquier duda o consulta, no dude en ponerse en contacto con nosotros, estamos a su disposición.</p>
          <%= form_for :contact_form, url: contact_path do |customer| %>
            <div class="form-group">
              <label for="InputName1">Nombre</label>
              <%= customer.text_field :name, class: "form-control"%>
            </div>
            <div class="form-group">
              <label for="InputEmail1">Email</label>
              <%= customer.email_field :email, class: "form-control"%>
            </div>
            <div class="form-group">
              <label for="InputSubject1">Asunto</label>
              <%= customer.text_field :subject, class: "form-control"%>
            </div>
            <div class="form-group">
              <label for="message1">Mensaje</label>
              <%= customer.text_area :message, class: "form-control", rows: "8" %>
            </div>
            <%= customer.submit 'Enviar', class: "btn btn-theme" %>
          <% end %>
      </div><!--/col-lg-8 -->
      
      <div class="col-lg-4">
        <h4>Datos adicionales</h4>
        <div class="hline"></div>
          <p>
            Boulogne Sur Mer,<br/>
            1275, General Pacheco,<br/>
            Argentina.<br/>
          </p>
          <p>
            <strong>Email:</strong> info@novopacheco.com<br/>
            <strong>Tel:</strong> 011 4736-0900
          </p>
          <p><strong>Horario de atención al público</strong><br> 9 a 21hs. de Lunes a Domingo</p>
      </div>
    </div><!--/row -->
   </div><!--/container -->

app/views/contact/send_message.html.erb
<h1><%= @message.name %></h1>
<h2><%= @message.email %></h2>
<h3><%= @message.subject%></h3>
<%= @message.message%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/ico/favicon.ico">
    <title>Novo Pacheco Shopping</title>
    <link rel="shortcut icon" href="http://s23.postimg.org/aur7o0c47/oie_transparent_1.png"/>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Lato:400,900' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,700,900' rel='stylesheet' type='text/css'>
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

  <!--/Feedback-->
    <div id="feedback">
      <div id="feedback-form" style='display:none;' class="col-xs-4 col-md-4 panel panel-default">
        <%= form_for :feedback, html: {class: "form panel-body"}, url: feedback_path do |customer| %>
          <div class="form-group">
            <%= customer.email_field :email, class: "form-control",
            placeholder: "Tu e-mail", autofocus: true%>
          </div>
          <div class="form-group">
            <%= customer.text_area :message, class: "form-control", 
            rows: "5", placeholder: "Sumate a nuestro shopping, agendemos una reunión" %>
          </div>
          <%= customer.submit 'Contactar', class: "btn btn-primary pull-right" %>
        <% end %>
      </div>
      <div id="feedback-tab">Sumate</div>
    </div>
  <!--/Feedback-->

  <%= yield %>

  <!-- *****************************************************************************************************************
     FOOTER
     ***************************************************************************************************************** -->
     <div id="footerwrap">
      <div class="container">
        <div class="row">
          <div class="col-lg-4">
            <h4>Novo Pacheco Shopping</h4>
            <div class="hline-w"></div>
            <p>Podrá vivir lindos momentos, entre familiares o amigos. Ir de compras, cenar o participar de divertidos talleres que se dictan en el lugar.</p>
          </div>
          <div class="col-lg-4">
            <h4>Redes sociales</h4>
            <div class="hline-w"></div>
            <p>
              <a href="https://www.facebook.com/NovoPacheco?fref=ts" target="_blank"><i class="fa fa-facebook"></i></a>
              <a href="#"><i class="fa fa-twitter"></i></a>
              <a href="#"><i class="fa fa-instagram"></i></a>
            </p>
          </div>
          <div class="col-lg-4">
            <h4>Contacto</h4>
            <div class="hline-w"></div>
            <p>
              011 4736-0900,<br/>
              info@novopacheco.com,<br/>
              <p>Powered by <strong><a href="http://linkedin.com/in/josevillegasl" target="_blank">Jose Villegas</a> |
                <a href="https://ar.linkedin.com/in/andresabed" target="_blank">Andres Abed</a>
              </strong></p>
            </p>
          </div>
        
        </div><!--/row -->
      </div><!--/container -->
     </div><!--/footerwrap -->

    <script>
      // Portfolio
      (function($) {
        "use strict";
        var $container = $('.portfolio'),
          $items = $container.find('.portfolio-item'),
          portfolioLayout = 'fitRows';
          
          if( $container.hasClass('portfolio-centered') ) {
            portfolioLayout = 'masonry';
          }
              
          $container.isotope({
            filter: '*',
            animationEngine: 'best-available',
            layoutMode: portfolioLayout,
            animationOptions: {
            duration: 750,
            easing: 'linear',
            queue: false
          },
          masonry: {
          }
          }, refreshWaypoints());
          
          function refreshWaypoints() {
            setTimeout(function() {
            }, 1000);   
          }
              
          $('nav.portfolio-filter ul a').on('click', function() {
              var selector = $(this).attr('data-filter');
              $container.isotope({ filter: selector }, refreshWaypoints());
              $('nav.portfolio-filter ul a').removeClass('active');
              $(this).addClass('active');
              return false;
          });
          
          function getColumnNumber() { 
            var winWidth = $(window).width(), 
            columnNumber = 1;
          
            if (winWidth > 1200) {
              columnNumber = 5;
            } else if (winWidth > 950) {
              columnNumber = 4;
            } else if (winWidth > 600) {
              columnNumber = 3;
            } else if (winWidth > 400) {
              columnNumber = 2;
            } else if (winWidth > 250) {
              columnNumber = 1;
            }
              return columnNumber;
            }       
            
            function setColumns() {
              var winWidth = $(window).width(), 
              columnNumber = getColumnNumber(), 
              itemWidth = Math.floor(winWidth / columnNumber);
              
              $container.find('.portfolio-item').each(function() { 
                $(this).css( { 
                width : itemWidth + 'px' 
              });
            });
          }
          
          function setPortfolio() { 
            setColumns();
            $container.isotope('reLayout');
          }
            
          $container.imagesLoaded(function () { 
            setPortfolio();
          });
          
          $(window).on('resize', function () { 
          setPortfolio();          
        });
      })(jQuery);
    </script>
  </body>
</html>

app/views/main/brands.html.erb
<!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img src="<%= image_path('logo.png') %>"></a>
        </div>
        <div class="navbar-collapse collapse navbar-right">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <li><a href="/about">Novo Pacheco</a></li>
            <li class="active"><a href="/marcas">Marcas</a></li>
            <li><a href="/contacto">Contacto</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <% if flash.notice %>
      <div class="alert alert-success">
        <%= flash.notice %>  
      </div>
    <% end %>
    <% if flash.alert %>
      <div class="alert alert-danger">
        <%= flash.alert %>  
      </div>
    <% end %>

   <div id="portfoliowrap" class="marcas">
    <h1 class="teventos">NUESTRAS MARCAS</h1>
    <p class="bajadamarcas">Si tenés una marca y querés sumarte a Novo Pacheco, consultá para tener una reunión</p>
    <a class="btn btn-lg btn-primary" href="https://docs.google.com/forms/d/1cs6XtZXC6RCvUYh9YN0AcSuMXcO7kcT1xWTLFRHIcOY/viewform?usp=send_form" role="button" target="_blank">Consultar aquí</a>

    <div class="portfolio-centered">
      <div class="recentitems portfolio">
        <% @brands.each do |b| %>
          <div class="portfolio-item graphic-design">
            <div class="he-wrap tpl6">
              <img src="<%= b.logo.url %>" alt="">
              <div class="he-view">
                <div class="bg a0" data-animate="fadeIn">
                  <h3 class="a1" data-animate="fadeInDown">Conocé el local</h3>
                  <a data-rel="prettyPhoto" href="<%= b.logo.url %>"></a>
                  <%= link_to 'Ver más', brand_path(b), class: 'dmbutton a2', "data-animate" => "fadeInUp"%>
                </div><!-- he bg -->
              </div><!-- he view -->    
            </div><!-- he wrap -->
          </div><!-- end col-12 -->
        <% end %>
      </div><!-- portfolio -->
    </div><!-- portfolio container -->
   </div><!--/Portfoliowrap -->

app/views/main/index.html.erb
<!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img src="<%= image_path('logo.png') %>"></a>
        </div>
        <div class="navbar-collapse collapse navbar-right">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="/about">Novo Pacheco</a></li>
            <li><a href="/marcas">Marcas</a></li>
            <li><a href="/contacto">Contacto</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <% if flash.notice %>
      <div class="alert alert-success">
        <%= flash.notice %>  
      </div>
    <% end %>
    <% if flash.alert %>
      <div class="alert alert-danger">
        <%= flash.alert %>  
      </div>
    <% end %>
  <!-- *****************************************************************************************************************
   HEADERWRAP
   ***************************************************************************************************************** -->
<section>
  <div id="carousel-id" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
          <li data-target="#carousel-id" data-slide-to="1" class=""></li>
          <li data-target="#carousel-id" data-slide-to="2" class="active"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item">
          <img src="<%= image_path('bg2.jpg') %>">
          <div class="container">
            <div class="carousel-caption">
              <h1>Sumate a Novo Pacheco</h1>
              <a class="btn btn-lg btn-primary" href="https://docs.google.com/forms/d/1cs6XtZXC6RCvUYh9YN0AcSuMXcO7kcT1xWTLFRHIcOY/viewform?usp=send_form" role="button" target="_blank">Consultar aquí</a>
            </div>
          </div>
        </div>
        <div class="item active">
          <img src="<%= image_path('bg1.jpg') %>">
          <div class="container">
            <div class="carousel-caption">
              <h1>Un lugar de encuentros</h1>
              <a href="about.html"><button class="btn btn-lg btn-primary" role="button">Ver fotos</button></a>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#carousel-id" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#carousel-id" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
  </div>
</section>

  <!-- *****************************************************************************************************************
   SERVICE LOGOS
   ***************************************************************************************************************** -->
   
   <h1 class="teventos">Promociones y Eventos</h1>

   <div id="service">
    <div class="container">
      <div class="row centered">
        <% @events.each do |e| %>
          <div class="col-md-4">
            <img src="<%= e.image.url %>">
            <h4><%= e.title %></h4>
            <p><%= e.description %></p>
          </div>
        <% end %>  
      </div>
    </div><!--/container -->
   </div><!--/service -->